[2015/Feb/10 16:48:48] CRITICAL [sikr:31] API started
[2015/Feb/10 16:48:48] INFO [sikr:35] Database connected
[2015/Feb/10 16:48:48] INFO [sikr:70] Application started
[2015/Feb/10 16:51:33] CRITICAL (sikr) [app.py:31] API started
[2015/Feb/10 16:51:33] INFO (sikr) [app.py:35] Database connected
[2015/Feb/10 16:51:33] INFO (sikr) [app.py:70] Application started
[2015/Feb/10 16:54:02] CRITICAL [sikr/app.py:31] API started
[2015/Feb/10 16:54:02] INFO [sikr/app.py:35] Database connected
[2015/Feb/10 16:54:02] INFO [sikr/app.py:70] Application started
[2015/Feb/10 16:54:21] CRITICAL [sikr/app.py:31] API started
[2015/Feb/10 16:54:21] INFO [sikr/app.py:35] Database connected
[2015/Feb/10 16:54:21] INFO [sikr/app.py:70] Application started
[2015/Feb/10 16:56:37] CRITICAL [sikr/app.py:31] API started
[2015/Feb/10 16:56:37] INFO [sikr/app.py:35] Database connected
[2015/Feb/10 16:56:37] INFO [sikr/app.py:70] Application started
[2015/Feb/10 16:58:28] CRITICAL [sikr/app.py:31] API started
[2015/Feb/10 16:58:28] INFO [sikr/app.py:35] Database connected
[2015/Feb/10 16:58:28] INFO [sikr/app.py:70] Application started
[2015/Feb/10 16:58:30] INFO [sikr/items.py:44] data awat!
[2015/02/10 17:37:40] DEBUG [app.py-><module>:59] API service started
[2015/02/10 17:39:11] DEBUG [app.py-><module>:59] API service started
[2015/02/10 17:39:13] DEBUG [items.py->on_get:63] Items request succesful
[2015/02/10 17:40:23] DEBUG [app.py-><module>:59] API service started
[2015/02/10 17:40:24] DEBUG [items.py->on_get:57] Items request succesful
[2015/02/10 17:42:55] DEBUG [app.py-><module>:59] API service started
[2015/02/10 17:42:59] ERROR [items.py->on_get:59] 'Service' object has no attribute 'nae'
[2015/02/10 17:46:29] DEBUG [app.py-><module>:60] API service started
[2015/02/10 17:46:32] DEBUG [items.py->on_get:57] Items request succesful
[2015/02/10 17:53:39] DEBUG [app.py-><module>:60] API service started
[2015/02/11 11:40:29] DEBUG [app.py-><module>:60] API service started
[2015/02/11 12:02:13] DEBUG [app.py-><module>:60] API service started
[2015/02/11 12:02:23] DEBUG [items.py->on_get:63] Items request succesful
[2015/02/11 12:02:31] ERROR [items.py->on_get:65] type object 'Item' has no attribute 'group'
[2015/02/11 12:03:06] DEBUG [app.py-><module>:60] API service started
[2015/02/11 12:03:10] ERROR [items.py->on_get:65] type object 'Item' has no attribute 'group'
[2015/02/11 12:03:44] DEBUG [app.py-><module>:60] API service started
[2015/02/11 12:03:45] ERROR [items.py->on_get:67] type object 'Item' has no attribute 'group'
[2015/02/11 14:45:32] INFO [models.py-><module>:180] Attempting to create the tables
[2015/02/11 14:45:32] ERROR [models.py-><module>:201] DB tables not created. Probably they already exist
[2015/02/11 14:45:32] DEBUG [app.py-><module>:60] API service started
[2015/02/11 14:45:43] ERROR [items.py->on_get:66] no such column: t1.group_id
[2015/02/11 14:45:44] ERROR [items.py->on_get:66] no such column: t1.group_id
[2015/02/11 14:45:46] ERROR [items.py->on_get:66] no such column: t1.group_id
[2015/02/11 14:45:48] ERROR [items.py->on_get:66] no such column: t1.group_id
[2015/02/11 14:46:27] INFO [models.py-><module>:180] Attempting to create the tables
[2015/02/11 14:46:27] ERROR [models.py-><module>:201] DB tables not created. Probably they already exist
[2015/02/11 14:46:27] DEBUG [app.py-><module>:60] API service started
[2015/02/11 14:46:28] ERROR [items.py->on_get:67] no such column: t1.group_id
[2015/02/11 14:46:29] ERROR [items.py->on_get:67] no such column: t1.group_id
[2015/02/11 14:47:20] INFO [models.py-><module>:180] Attempting to create the tables
[2015/02/11 14:47:20] ERROR [models.py-><module>:201] DB tables not created. Probably they already exist
[2015/02/11 14:47:20] DEBUG [app.py-><module>:60] API service started
[2015/02/11 14:47:22] ERROR [items.py->on_get:67] no such column: t1.group_id
[2015/02/11 14:48:00] INFO [models.py-><module>:180] Attempting to create the tables
[2015/02/11 14:48:00] ERROR [models.py-><module>:201] DB tables not created. Probably they already exist
[2015/02/11 14:48:00] DEBUG [app.py-><module>:60] API service started
[2015/02/11 14:48:02] ERROR [items.py->on_get:68] no such column: t1.group_id
[2015/02/11 14:48:16] INFO [models.py-><module>:180] Attempting to create the tables
[2015/02/11 14:48:16] ERROR [models.py-><module>:201] DB tables not created. Probably they already exist
[2015/02/11 14:48:16] DEBUG [app.py-><module>:60] API service started
[2015/02/11 14:48:18] ERROR [items.py->on_get:69] no such column: t1.group_id
[2015/02/11 14:48:53] INFO [models.py-><module>:180] Attempting to create the tables
[2015/02/11 14:48:53] ERROR [models.py-><module>:201] DB tables not created. Probably they already exist
[2015/02/11 14:48:53] DEBUG [app.py-><module>:60] API service started
[2015/02/11 14:51:31] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 14:51:31] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 14:51:31] DEBUG [app.py-><module>:60] API service started
[2015/02/11 14:51:33] ERROR [items.py->on_get:71] local variable 'item' referenced before assignment
[2015/02/11 14:52:03] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 14:52:03] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 14:52:03] DEBUG [app.py-><module>:60] API service started
[2015/02/11 14:52:04] ERROR [items.py->on_get:72] local variable 'item' referenced before assignment
[2015/02/11 14:52:17] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 14:52:17] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 14:52:17] DEBUG [app.py-><module>:60] API service started
[2015/02/11 14:52:19] ERROR [items.py->on_get:72] no such column: t1.group_id
[2015/02/11 14:53:51] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 14:53:51] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 14:53:51] DEBUG [app.py-><module>:60] API service started
[2015/02/11 14:53:54] ERROR [items.py->on_get:72] no such column: t1.group_id
[2015/02/11 14:54:41] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 14:54:41] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 14:54:41] DEBUG [app.py-><module>:60] API service started
[2015/02/11 14:54:46] ERROR [items.py->on_get:72] no such column: t1.group_id
[2015/02/11 14:54:47] ERROR [items.py->on_get:72] no such column: t1.group_id
[2015/02/11 14:54:47] ERROR [items.py->on_get:72] no such column: t1.group_id
[2015/02/11 14:54:47] ERROR [items.py->on_get:72] no such column: t1.group_id
[2015/02/11 14:54:47] ERROR [items.py->on_get:72] no such column: t1.group_id
[2015/02/11 14:55:13] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 14:55:13] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 14:55:13] DEBUG [app.py-><module>:60] API service started
[2015/02/11 14:55:14] ERROR [items.py->on_get:72] no such column: t1.group_id
[2015/02/11 14:56:47] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 14:56:47] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 14:56:47] DEBUG [app.py-><module>:60] API service started
[2015/02/11 14:56:50] ERROR [items.py->on_get:72] no such column: t1.group_id
[2015/02/11 14:57:42] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 14:57:42] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 14:57:42] DEBUG [app.py-><module>:60] API service started
[2015/02/11 14:57:46] ERROR [items.py->on_get:72] no such column: t1.group_id
[2015/02/11 14:59:57] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 14:59:57] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 14:59:57] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:00:04] ERROR [items.py->on_get:72] 'Node' object has no attribute 'rhs'
[2015/02/11 15:00:28] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:00:28] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:00:28] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:00:31] ERROR [items.py->on_get:72] 'Node' object has no attribute 'rhs'
[2015/02/11 15:00:48] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:00:48] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:00:48] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:00:52] ERROR [items.py->on_get:72] name 'json' is not defined
[2015/02/11 15:02:02] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:02:02] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:02:02] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:02:06] ERROR [items.py->on_get:74] name 'json' is not defined
[2015/02/11 15:04:54] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:04:54] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:04:54] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:04:59] ERROR [items.py->on_get:74] no such column: t1.group_id
[2015/02/11 15:05:23] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:05:23] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:05:23] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:05:25] ERROR [items.py->on_get:74] 'NaiveQueryResultWrapper' object has no attribute 'dicts'
[2015/02/11 15:05:46] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:05:46] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:05:46] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:05:47] ERROR [items.py->on_get:74] no such column: t1.group_id
[2015/02/11 15:06:18] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:06:18] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:06:18] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:06:21] ERROR [items.py->on_get:74] no such column: t1.group_id
[2015/02/11 15:07:19] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:07:19] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:07:19] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:07:22] ERROR [items.py->on_get:76] no such column: t2.id
[2015/02/11 15:07:46] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:07:46] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:07:46] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:07:48] ERROR [items.py->on_get:76] 'Service' object is not iterable
[2015/02/11 15:08:24] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:08:24] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:08:24] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:08:26] ERROR [items.py->on_get:76] 'Service' object is not iterable
[2015/02/11 15:09:08] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:09:08] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:09:08] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:09:09] ERROR [items.py->on_get:76] 'Service' object is not iterable
[2015/02/11 15:09:25] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:09:25] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:09:25] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:09:27] ERROR [items.py->on_get:76] no such column: t1.group_id
[2015/02/11 15:11:00] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:11:00] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:11:00] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:11:03] ERROR [items.py->on_get:76] 'NaiveQueryResultWrapper' object has no attribute 'dicts'
[2015/02/11 15:11:20] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:11:20] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:11:20] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:11:23] ERROR [items.py->on_get:76] no such column: t1.group_id
[2015/02/11 15:13:54] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:13:54] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:13:54] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:13:56] ERROR [items.py->on_get:71] no such column: t1.group_id
[2015/02/11 15:14:13] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:14:13] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:14:13] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:14:14] ERROR [items.py->on_get:71] no such column: t1.group_id
[2015/02/11 15:14:39] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:14:39] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:14:47] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:14:47] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:14:47] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:14:48] ERROR [items.py->on_get:72] no such column: t1.group_id
[2015/02/11 15:15:11] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:15:11] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:15:11] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:15:14] ERROR [items.py->on_get:73] no such column: t1.group_id
[2015/02/11 15:16:22] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:16:22] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:16:22] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:16:24] ERROR [items.py->on_get:75] no such column: t1.group_id
[2015/02/11 15:18:04] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:18:04] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:18:04] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:18:05] ERROR [items.py->on_get:77] no such column: t1.group_id
[2015/02/11 15:19:41] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:19:41] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:19:41] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:19:42] ERROR [items.py->on_get:77] dump() missing 1 required positional argument: 'fp'
[2015/02/11 15:19:56] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:19:56] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:19:56] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:19:57] ERROR [items.py->on_get:77] <sikre.models.models.Service object at 0x7fb702c70898> is not JSON serializable
[2015/02/11 15:21:53] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:21:53] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:21:53] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:21:55] ERROR [items.py->on_get:78] <sikre.models.models.Service object at 0x7fd6832d28d0> is not JSON serializable
[2015/02/11 15:22:14] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:22:14] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:22:14] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:22:16] ERROR [items.py->on_get:78] 'Service' object has no attribute 'dicts'
[2015/02/11 15:22:36] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:22:36] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:22:36] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:22:39] ERROR [items.py->on_get:78] 'Service' object is not iterable
[2015/02/11 15:22:55] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:22:55] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:22:55] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:22:57] ERROR [items.py->on_get:78] 'Service' object is not iterable
[2015/02/11 15:23:37] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:23:37] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:24:01] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:24:01] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:24:01] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:24:04] ERROR [items.py->on_get:78] no such column: t1.group_id
[2015/02/11 15:25:07] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:25:07] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:25:07] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:25:09] ERROR [items.py->on_get:78] no such column: t1.group_id
[2015/02/11 15:25:26] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:25:26] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:25:26] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:25:27] ERROR [items.py->on_get:78] no such column: t1.group_id
[2015/02/11 15:26:11] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:26:11] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:26:11] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:26:13] ERROR [items.py->on_get:78] no such column: t1.group_id
[2015/02/11 15:26:49] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:26:49] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:26:49] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:26:52] ERROR [items.py->on_get:78] no such column: t1.group_id
[2015/02/11 15:27:04] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:27:04] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:27:04] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:27:06] ERROR [items.py->on_get:78] no such column: t1.group_id
[2015/02/11 15:29:51] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:29:51] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:29:51] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:29:59] ERROR [items.py->on_get:78] no such column: t1.group_id
[2015/02/11 15:30:36] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:30:36] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:30:36] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:30:39] ERROR [items.py->on_get:78] no such column: t1.group_id
[2015/02/11 15:32:26] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:32:26] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:32:26] DEBUG [app.py-><module>:60] API service started
[2015/02/11 15:32:27] ERROR [items.py->on_get:75] no such column: t1.group_id
[2015/02/11 15:33:00] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:33:02] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:33:09] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:33:11] ERROR [models.py-><module>:202] DB tables not created. Probably they already exist
[2015/02/11 15:35:01] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:35:23] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:40:14] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:42:24] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 15:43:42] INFO [models.py-><module>:187] Attempting to create the tables
[2015/02/11 15:43:44] ERROR [models.py-><module>:199] DB tables not created. Probably they already exist
[2015/02/11 15:44:27] INFO [models.py-><module>:187] Attempting to create the tables
[2015/02/11 15:44:30] ERROR [models.py-><module>:199] DB tables not created. Probably they already exist
[2015/02/11 15:45:09] INFO [models.py-><module>:180] Attempting to create the tables
[2015/02/11 16:09:42] INFO [models.py-><module>:180] Attempting to create the tables
[2015/02/11 16:09:42] ERROR [models.py-><module>:192] DB tables not created. Probably they already exist
[2015/02/11 16:09:58] INFO [models.py-><module>:180] Attempting to create the tables
[2015/02/11 16:21:35] INFO [models.py-><module>:180] Attempting to create the tables
[2015/02/11 16:21:56] INFO [models.py-><module>:180] Attempting to create the tables
[2015/02/11 16:22:50] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:23:06] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:23:06] ERROR [models.py-><module>:194] DB tables not created. Probably they already exist
[2015/02/11 16:25:03] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:25:58] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:26:45] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:31:46] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:34:35] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:35:34] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:38:22] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:39:29] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:41:24] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:42:42] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:44:19] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:49:38] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:49:58] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:50:09] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:50:55] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:53:06] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:53:33] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:53:49] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:54:37] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:55:46] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:55:46] ERROR [models.py-><module>:194] DB tables not created. Probably they already exist
[2015/02/11 16:55:51] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:56:38] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:57:10] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:58:03] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:58:31] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:59:03] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:59:26] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 16:59:49] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 17:00:46] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 17:01:51] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 17:04:34] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 17:05:11] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 17:07:03] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 17:07:03] ERROR [models.py-><module>:194] DB tables not created. Probably they already exist
[2015/02/11 17:09:17] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 17:09:17] ERROR [models.py-><module>:194] DB tables not created. Probably they already exist
[2015/02/11 17:09:17] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:09:27] ERROR [items.py->on_get:67] type object 'Service' has no attribute 'pk'
[2015/02/11 17:09:41] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 17:09:41] ERROR [models.py-><module>:194] DB tables not created. Probably they already exist
[2015/02/11 17:09:41] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:09:43] DEBUG [items.py->on_get:64] Items request succesful
[2015/02/11 17:13:13] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 17:13:13] ERROR [models.py-><module>:194] DB tables not created. Probably they already exist
[2015/02/11 17:13:13] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:13:16] ERROR [items.py->on_get:55] 'Item' object does not support item assignment
[2015/02/11 17:13:45] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 17:13:45] ERROR [models.py-><module>:194] DB tables not created. Probably they already exist
[2015/02/11 17:13:45] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:13:46] ERROR [items.py->on_get:55] int() argument must be a string or a number, not 'dict'
[2015/02/11 17:14:12] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 17:14:12] ERROR [models.py-><module>:194] DB tables not created. Probably they already exist
[2015/02/11 17:14:12] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:14:14] ERROR [items.py->on_get:55] int() argument must be a string or a number, not 'dict'
[2015/02/11 17:14:56] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 17:14:56] ERROR [models.py-><module>:194] DB tables not created. Probably they already exist
[2015/02/11 17:14:56] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:14:57] DEBUG [items.py->on_get:51] Items request succesful
[2015/02/11 17:17:29] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 17:17:29] ERROR [models.py-><module>:194] DB tables not created. Probably they already exist
[2015/02/11 17:17:44] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 17:17:44] ERROR [models.py-><module>:194] DB tables not created. Probably they already exist
[2015/02/11 17:22:42] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 17:22:42] ERROR [models.py-><module>:194] DB tables not created. Probably they already exist
[2015/02/11 17:22:42] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:22:47] DEBUG [items.py->on_get:53] Items request succesful
[2015/02/11 17:36:53] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 17:36:53] ERROR [models.py-><module>:194] DB tables not created. Probably they already exist
[2015/02/11 17:36:53] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:36:56] DEBUG [items.py->on_get:54] Items request succesful
[2015/02/11 17:38:58] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 17:38:58] ERROR [models.py-><module>:194] DB tables not created. Probably they already exist
[2015/02/11 17:38:58] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:39:00] DEBUG [items.py->on_get:56] Items request succesful
[2015/02/11 17:39:05] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 17:39:05] ERROR [models.py-><module>:194] DB tables not created. Probably they already exist
[2015/02/11 17:39:05] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:39:07] ERROR [items.py->on_get:59] type object 'Item' has no attribute 'descripion'
[2015/02/11 17:40:57] INFO [models.py-><module>:181] Attempting to create the tables
[2015/02/11 17:40:57] ERROR [models.py-><module>:194] DB tables not created. Probably they already exist
[2015/02/11 17:40:57] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:40:58] DEBUG [items.py->on_get:56] Items request succesful
[2015/02/11 17:41:02] ERROR [items.py->on_get:59] 'Item' object is not subscriptable
[2015/02/11 17:47:05] INFO [models.py-><module>:176] Attempting to create the tables
[2015/02/11 17:47:05] ERROR [models.py-><module>:189] DB tables not created. Probably they already exist
[2015/02/11 17:47:05] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:47:08] ERROR [items.py->on_get:60] 'id'
[2015/02/11 17:47:48] INFO [models.py-><module>:176] Attempting to create the tables
[2015/02/11 17:47:48] ERROR [models.py-><module>:189] DB tables not created. Probably they already exist
[2015/02/11 17:47:48] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:47:49] ERROR [items.py->on_get:61] 'id'
[2015/02/11 17:48:05] INFO [models.py-><module>:176] Attempting to create the tables
[2015/02/11 17:48:05] ERROR [models.py-><module>:189] DB tables not created. Probably they already exist
[2015/02/11 17:48:05] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:48:06] ERROR [items.py->on_get:62] 'id'
[2015/02/11 17:48:31] INFO [models.py-><module>:176] Attempting to create the tables
[2015/02/11 17:48:31] ERROR [models.py-><module>:189] DB tables not created. Probably they already exist
[2015/02/11 17:48:31] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:48:33] ERROR [items.py->on_get:62] 'ForeignKeyField' object has no attribute 'id'
[2015/02/11 17:49:49] INFO [models.py-><module>:176] Attempting to create the tables
[2015/02/11 17:49:49] ERROR [models.py-><module>:189] DB tables not created. Probably they already exist
[2015/02/11 17:49:49] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:49:51] ERROR [items.py->on_get:63] 'id'
[2015/02/11 17:50:13] INFO [models.py-><module>:176] Attempting to create the tables
[2015/02/11 17:50:13] ERROR [models.py-><module>:189] DB tables not created. Probably they already exist
[2015/02/11 17:50:13] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:50:14] ERROR [items.py->on_get:63] 'ItemGroup' object has no attribute 'dicts'
[2015/02/11 17:51:39] INFO [models.py-><module>:176] Attempting to create the tables
[2015/02/11 17:51:39] ERROR [models.py-><module>:189] DB tables not created. Probably they already exist
[2015/02/11 17:51:39] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:51:42] ERROR [items.py->on_get:64] 'id'
[2015/02/11 17:52:23] INFO [models.py-><module>:176] Attempting to create the tables
[2015/02/11 17:52:23] ERROR [models.py-><module>:189] DB tables not created. Probably they already exist
[2015/02/11 17:52:23] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:52:25] ERROR [items.py->on_get:64] 'id'
[2015/02/11 17:52:54] INFO [models.py-><module>:176] Attempting to create the tables
[2015/02/11 17:52:54] ERROR [models.py-><module>:189] DB tables not created. Probably they already exist
[2015/02/11 17:52:54] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:52:55] ERROR [items.py->on_get:62] 'id'
[2015/02/11 17:53:21] INFO [models.py-><module>:176] Attempting to create the tables
[2015/02/11 17:53:21] ERROR [models.py-><module>:189] DB tables not created. Probably they already exist
[2015/02/11 17:53:21] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:53:22] ERROR [items.py->on_get:63] 'id'
[2015/02/11 17:53:38] INFO [models.py-><module>:176] Attempting to create the tables
[2015/02/11 17:53:38] ERROR [models.py-><module>:189] DB tables not created. Probably they already exist
[2015/02/11 17:53:38] DEBUG [app.py-><module>:60] API service started
[2015/02/11 17:53:40] DEBUG [items.py->on_get:59] Items request succesful
[2015/02/11 17:53:44] DEBUG [items.py->on_get:59] Items request succesful
[2015/02/11 17:58:29] INFO [models.py-><module>:176] Attempting to create the tables
[2015/02/11 18:01:44] INFO [models.py-><module>:176] Attempting to create the tables
[2015/02/11 18:01:44] ERROR [models.py-><module>:189] DB tables not created. Probably they already exist
[2015/02/11 18:01:44] DEBUG [app.py-><module>:60] API service started
[2015/02/11 18:01:47] DEBUG [items.py->on_get:44] Got items filtered by group
[2015/02/11 18:01:47] DEBUG [items.py->on_get:57] Items request succesful
[2015/02/11 18:01:51] DEBUG [items.py->on_get:48] Got all items
[2015/02/11 18:01:51] DEBUG [items.py->on_get:57] Items request succesful
[2015/02/11 18:01:54] INFO [models.py-><module>:176] Attempting to create the tables
[2015/02/11 18:01:54] ERROR [models.py-><module>:189] DB tables not created. Probably they already exist
[2015/02/11 18:01:54] DEBUG [app.py-><module>:60] API service started
[2015/02/11 18:23:32] INFO [models.py-><module>:176] Attempting to create the tables
[2015/02/11 18:23:32] ERROR [models.py-><module>:189] DB tables not created. Probably they already exist
[2015/02/11 18:37:27] INFO [models.py-><module>:176] Attempting to create the tables
[2015/02/11 18:37:27] ERROR [models.py-><module>:189] DB tables not created. Probably they already exist
[2015/02/11 18:46:45] DEBUG [app.py->main_api_loop:60] API service started
[2015/02/11 18:49:17] DEBUG [app.py->main_api_loop:60] API service started
[2015/02/11 18:50:08] DEBUG [app.py->main_api_loop:60] API service started
[2015/02/11 18:50:42] DEBUG [app.py-><module>:77] API service started
[2015/02/11 18:50:44] DEBUG [items.py->on_get:50] Got all items
[2015/02/11 18:50:44] DEBUG [items.py->on_get:59] Items request succesful
[2015/02/11 18:50:56] DEBUG [app.py-><module>:74] API service started
[2015/02/11 18:52:25] INFO [generator.py->generate_database:37] Starting database generation
[2015/02/11 18:52:28] INFO [generator.py->generate_database:59] Admin user not created. You can create it afterwards.

[2015/02/11 18:52:58] INFO [syncdb.py->generate_db_schema:24] Attempting to create the tables
[2015/02/11 18:53:04] INFO [generator.py->generate_database:37] Starting database generation
[2015/02/11 18:53:06] INFO [generator.py->generate_database:59] Admin user not created. You can create it afterwards.

[2015/02/11 18:54:01] INFO [syncdb.py->generate_db_schema:24] Attempting to create the tables
[2015/02/11 18:54:07] INFO [generator.py->generate_database:37] Starting database generation
[2015/02/11 18:54:09] INFO [generator.py->generate_database:59] Admin user not created. You can create it afterwards.

[2015/02/11 18:54:25] INFO [syncdb.py->generate_db_schema:24] Attempting to create the tables
[2015/02/11 18:54:30] INFO [syncdb.py->generate_db_schema:24] Attempting to create the tables
[2015/02/11 18:54:36] INFO [generator.py->generate_database:37] Starting database generation
[2015/02/11 18:54:38] INFO [generator.py->generate_database:59] Admin user not created. You can create it afterwards.

[2015/02/11 18:55:05] INFO [generator.py->generate_database:105] Database generation completed successfully
[2015/02/11 18:55:15] DEBUG [app.py-><module>:74] API service started
[2015/02/11 18:55:16] DEBUG [items.py->on_get:50] Got all items
[2015/02/11 18:55:17] DEBUG [items.py->on_get:59] Items request succesful
[2015/02/11 18:55:17] DEBUG [items.py->on_get:50] Got all items
[2015/02/11 18:55:17] DEBUG [items.py->on_get:59] Items request succesful
